ARG ORA_VERSION

FROM relloyd/halfpipe-oracle-${ORA_VERSION}:latest

USER root

# AWS CLI

RUN apt-get update -y \
    && apt-get install -y curl less vim libaio1 ca-certificates unzip glibc-source groff \
    && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm awscliv2.zip

# Kubectl

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x ./kubectl \
    && mv ./kubectl /usr/local/bin/kubectl \
    && echo "alias k=kubectl" >> .bashrc

# K9s

RUN mkdir -p /usr/local/k9s \
    && cd /usr/local/k9s \
    && curl -L https://github.com/derailed/k9s/releases/download/v0.25.18/k9s_Linux_x86_64.tar.gz -o k9s.tar.gz \
    && tar xvzf k9s.tar.gz \
    && rm k9s.tar.gz \
    && chmod +x k9s \
    && ln -s /usr/local/k9s/k9s /usr/local/bin/k9s \
    && echo "export TERM=xterm-256color" >> /home/dataops/.bashrc

USER dataops

# Scripts

COPY --chown=dataops:dataops scripts/configure.sh /home/dataops/
COPY --chown=dataops:dataops scripts/.template-variables.env /home/dataops/

WORKDIR /home/dataops
