FROM golang:alpine

ARG ORA_VERSION

ENV LD_LIBRARY_PATH /usr/glibc-compat/lib:/usr/glibc-compat/lib64:/usr/lib/instantclient
ENV PKG_CONFIG_PATH=/usr/local/pkg-config
ENV PATH "/usr/glibc-compat/sbin:/usr/glibc-compat/bin:$PATH:/go/bin:."
ENV NLS_LANG "ENGLISH_UNITED KINGDOM.AL32UTF8"
ENV GO111MODULE=on

COPY instantclient*$ORA_VERSION*.zip /tmp/

# libdl.so.2 expected by libclntsh.so
# libnsl.so.1 expected by libclntsh.so

#&& ln -s /lib64/ld-linux-x86-64.so.2 /usr/lib/libdl.so.2 \
#&& ln -s /lib64/ld-linux-x86-64.so.2 /usr/lib/ld-linux-x86-64.so.2 \
#&& ln -s /lib/libc.so.6 /usr/lib/libresolv.so.2 \
#&& ln -s /usr/lib/libnsl.so.2 /usr/lib/libnsl.so.1 \

#&& ln -s /usr/lib/instantclient/libclntsh.so.19.1 /usr/lib/libclntsh.so \
#    && ln -s /usr/lib/instantclient/libclntshcore.so.19.1 /usr/lib/libclntshcore.so \
#    && ln -s /usr/lib/instantclient/libocci.so.19.1 /usr/lib/libocci.so \
#    && ln -s /usr/lib/instantclient/libociei.so /usr/lib/libocci.so \
#    && ln -s /usr/lib/instantclient/libnnz19.so /usr/lib/libnnz19.so \

#    && apk add --no-cache libaio libnsl musl-dev libc-dev gcc pkgconfig git make openssh wget curl \

# causes failure when glibc-compat/sbin and bin are not in PATH:
#    && cp -rp /usr/glibc-compat/include/* /usr/include \

#    && mv instantclient* /usr/lib/instantclient \
#    && mv /usr/lib/instantclient/sdk/include/* /usr/include \

# Using /usr/glibc-compat/include as the include path does not work due to errors like: "/usr/glibc-compat/include/bits/local_lim.h:38:10: fatal error: linux/limits.h: No such file or directory"


RUN apk update \
    && apk add --no-cache musl-dev libc-dev libaio gcc pkgconfig git make openssh wget curl \
    && cd /tmp \
    && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
    && wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.32-r0/glibc-2.32-r0.apk \
    && wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.32-r0/glibc-dev-2.32-r0.apk \
    && wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.32-r0/glibc-bin-2.32-r0.apk \
    && wget -q https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.32-r0/glibc-i18n-2.32-r0.apk \
    && apk add glibc-2.32-r0.apk glibc-dev-2.32-r0.apk glibc-bin-2.32-r0.apk glibc-i18n-2.32-r0.apk \
    && for i in instantclient*$ORA_VERSION*.zip; do unzip "$i"; done \
    && rm instantclient*$ORA_VERSION*.zip \
    && mv instantclient*/sdk/include/* /usr/include \
    && mv instantclient* /usr/lib/instantclient \
    && mkdir -p "$PKG_CONFIG_PATH" \
    && mkdir -p /root/.ssh \
    && chmod 600 /root/.ssh \
    && git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/" \
    && ssh-keyscan gitlab.com >> /root/.ssh/known_hosts

CMD ["/bin/sh"]
